### ISSUE TITLE
The "Search Help Video" Link is wrong

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#11]
The menu item "Search Help Video" takes you to wrong video--it takes you to that old Facebook video which was a placeholder until the help video was finished.  

![image](https://user-images.githubusercontent.com/4837554/124814723-5c9cb780-df34-11eb-9584-e57ff7b11d70.png)

I bugged that in the client, but didn't realize it's an admin setting (odd because it's the only menu action controlled by admin).  But maybe they did that because we told them it was just a placeholder and it needs to be changed later.

In any case, the Admin settings needs to change it on stage Admin to:

http://support.pep-web.org/the-new-pep-web/pep-web-2021-video-tutorials/pep-web-2021-video-tutorial-search/

or wherever you want it to go, and then I'll push it to production when you let me know.

The setting is in General Settings, here:

![image](https://user-images.githubusercontent.com/4837554/124815423-40e5e100-df35-11eb-8c97-b20fd02ede90.png)

**Comment by PEPWebAdmin** [comment]
This now contains the correct video link on Stage. (I didn't do this though, perhaps David did?)

**Comment by nrshapiro** [comment]
Great.  This has been pushed to production.
