### ISSUE TITLE
Seeing a lot of Repetition of Expert Pick Graphics

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#12]
I've noticed a lot of repetition of the expert pick graphics which cannot be explained by the random pick algorithm...so I was investigating that this morning.  I see that all the graphic IDs in the queue are specified.  I believe this is the problem.

There are two ways to get an expert pick graphic.  

1) If you put a graphic ID next to the expert article pick ID, you will get that graphic, by design.  This is meant to allow you to intentionally pick a two related expert picks (article and graphic).
2) If you leave the graphic ID blank when you enter the expert article, the graphic will be selected randomly from the graphics in the PhotosInterestingforPOTD folder on dropbox.

**The easy solution to this is: when you don't intend to select the graphic manually, leave the graphic id blank in the queue.  It will then be picked randomly on the day that pick comes up.**  

FYI: @nadinelevinson

**Comment by PEPWebAdmin** [comment]
Thanks Neil - I haven't had any input into the Graphic of the Day so far, so I'm just including @SophieMBennett in this thread in case she hasn't seen this message.
