### ISSUE TITLE
Annual Production Process Setup

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#13]
We don't yet have the system set up for annual production of new journals and books.

Each year, we add _X_ new journals, potentially some new books, and release a "new PEP-Web" on January 22 (approximately).  _This year we are adding around 5 new journals!_  So we need to handle this relatively quickly.

To get data in place for that release we put it in PEPFuture, which only shows up on stage.  Then when we are ready to release, we move that data to PEPArchive and PEPCurrent as applicable.

So: we need a means to put data in PEPFuture on Stage, and have those items show up in PEP-Web Stage, but not be pushed to Production during normal push processing, or more likely, since everything is pushed when we push Solr, to make it such that PEPFuture does not show up on production.  Not just the articles, but the journal names and books which appear in the browse listing.  They should show up on Stage, for testing and proofing, but not on Production.

That will likely need to be done at the client, server and PaDS levels, and may also involve DevOps based processing.  

Open for Ideas and discussion below.

**Comment by nrshapiro** [comment]
I am wondering if we can do this a bit differently this year, and in coming years.  Here's a proposal, which fits well into the current process, and will be very easy to implement.

1.  All new data to go into PEPFuture category (this isn't different).  That of course includes the data that goes into Archive as well as Current when we release.
2.  All new data will appear in Stage and Production as the database is pushed weekly, but will be abstract-only, similar to PEPCurrent, but with a different message indicating that this data is being shown as a prerelease for the coming year.  
3. In January, as usual the week of the 22nd, I will move the data to the appropriate release category (Archive or Current).  We will push to production on the 22nd, announce the new release, and the data in the PEPArchive category will be fully readable to paid customers.

This is a very simple way to do things...and requires little to no development beyond the usual process.  

1) The new Journal parameters need to be added to my preproduction software
2) The new Journal names etc. need to be added to PaDS 
3) PEPFuture needs to be added to PaDS as a restricted, abstract only category as with PEPCurrent, if it's not already done
4) A message about the restriction needs to be added to PaDS and/or the Client comparable to PEPCurrent but with a description of the article being "preview" for the next release
5) If not already done, PEPFuture needs to be added to the normal processing code throughout the system so it's also put into the server databases.

@davidtuckett @nadinelevinson  - What do you think?

**Comment by jwoosnam** [comment]
Responding to Neil's second set of numbered items:

   1. na
   2. If they appear in the metadata Books, Journals & Videos API they will
   be picked up automatically by PaDS
   3. Pads doesn't really have the same concept of current and future, it
   just has documents that have a year and a number of embargoed years and
   calculates embargoed and non-embargoed from that.  This will work fine for
   journal articles and I think will also work for books and videos, but I am
   not sure.  We may have to populate the embargoed years against books and
   videos with 1 to ensure the new ones remain as abstracts.
   4. PEPFuture will be automatically embargoed.
   5. na

**Comment by nrshapiro** [comment]
To update this conversation with the results of our meeting yesterday:

I've updated the stage API to return accessClassification (as used elsewhere) which will return future for journals and books set for the future, which should be embargoed (with special users, like myself, and some journal editor accounts TBD, getting an override).

Example partial response:

    "responseSet": [
      {
        "sourceType": "journal",
        "PEPCode": "JPT",
        "bannerURL": "http://development.org:9100/v2/Documents/Image/bannerJPTLogo.gif",
        "displayTitle": "*New* Journal of Psychological Therapies",
        "srcTitle": "*New* Journal of Psychological Therapies",
        "title": "*New* Journal of Psychological Therapies",
        "abbrev": "J. Psych. Ther.",
        "ISSN": "2632-2099",
        "language": null,
        "yearFirst": "2016",
        "yearLast": "2021",
        "instanceCount": 105,
        "embargoYears": "3",
        "accessClassification": "future",
        "pubSourceURL": null,
        "PEPRelease": "2022"
      },
      {
        "sourceType": "journal",
        "PEPCode": "OEDA",
        "bannerURL": "http://development.org:9100/v2/Documents/Image/bannerOEDALogo.gif",
        "displayTitle": "*New* Oedipus Annual - Greek Annual Psychoanalytic Review",
        "srcTitle": "*New* Oedipus Annual - Greek Annual Psychoanalytic Review",
        "title": "*New* Oedipus Annual - Greek Annual Psychoanalytic Review",
        "abbrev": "Oed. Ann.",
        "ISSN": "1791-8472",
        "language": null,
        "yearFirst": "2020",
        "yearLast": "2021",
        "instanceCount": 21,
        "embargoYears": "3",
        "accessClassification": "future",
        "pubSourceURL": null,
        "PEPRelease": "2022"
      },

The definition of accessClassification (same as elsewhere in return models, though I've changed the examples below to show that these are returned all lowercase):

    accessClassification: str = Field(None, title="Document classification, e.g., archive, current, free, offsite")

Note that there's no 'current' that will ever be returned at **the journal level** since journals are often both pepcurrent and peparchive, but pepcurrent is simply determined by the embargo.

Note also I added PEPRelease which will show the release year on PEP-Web (or PEP-CD/DVD as applicable) of any journal.  PEPFuture for this year is set to 2022--the release will be on 1/22 (hopefully).

**Comment by nrshapiro** [comment]
As a side note, srcTitle is deprecated -- it was from v1-- but I've left it in for now because the Client is using that.  Use title instead please.  All the return models can be found at the end of the interactive API document/test site (i.e., stage-api.](https://stage-api.pep-web.org/docs#) after all the API calls  For example:

![image](https://user-images.githubusercontent.com/4837554/144261101-34ae7c40-a4f4-4b41-9310-e89dcaa12fb6.png)
