### ISSUE TITLE
Solved -- How to Do  an "On Site" Release Announcement

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#15]
@davidtuckett @nadinelevinson @rickardnyman @ocappello 

As I discussed with @SophieMBennett I'm no longer editing the WordPress site so I'll leave the announcement of 2022 to her.

But since we no longer have a "news" thread on pep-web, it is a more difficult issue to provide some sort of announcement there.  After all, not everyone is going to go to the support site every day to see what's new.  

**And I had an idea how to do it!**  

We have a popup facility built into the admin system which lets us design any popup for any use, and it's HTML based so it can handle formatting.  So I've drafted an announcement, you can edit it to your hearts content in the Admin pages.  

The next question is, where to link the popup.  I thought about putting it in our new message system, but you can't put links there, and we wouldn't want it there more than a day or so.

So looking at the home page top infoboxes, the right one was shorter than the left -- just enough room to add two lines for an announcement link.  I've done that on Stage.  Just as a sample.  You can do with it as you like, I mainly did it to show you a mechanism to accomplish this without losing or changing your current front page material.  Just look at the right info box in HTML to see how I did the linking, and then you can move it wherever you like (or omit it all together).  And you can use my sample write up as a starting draft on whatever you want to write and release.  I also included a graphic to show you how that's done.  Graphic files need to be in JPEG and loaded to s3s://s3.amazonaws.com/pep-web-gui which I can do for you, if you supply a different graphic(s).   I did this all relatively quickly, as I already have too many things on my plate.

Note whomever is in charge of editing Admin (Sophie?) will also have to change the other messages before we go live.  There are 84 journals now, if you include PCAS (we might want to wait until the official release of that, so 83).  I have to run my statistics to give you the number of articles...I'll post that in a reply to this tomorrow sometime.

When we go live, remember Admin gets "pushed" to stage so this goes on production then.  Meanwhile you can try out what you like, though remember there's no backup created when things are edited here.

**Comment by SophieMBennett** [comment]
I've now updated the total number of articles across the language settings on Stage. I counted 83 in total - including the 4 new, and PCAS and IJPOpen - from the Browse list of journals on Stage - are there any missing here? On Production the list currently has 77 titles.

Amendments to release text - see attached Word doc.

Front page header - simplified slightly to take account of the need to translate it.

Pop-up content. I've blended in some of the style of previous release messages and simplified other parts.
@nrshapiro please confirm the embargo dates are correct. 

@davidtuckett The IJPOpen info - is this correct, and is it best to keep it brief?

Developments to website - I've added a reminder about subscribers using the Help menu for feedback/issues.

Once it's agreed, should it be translated for the language settings?

[2022 release - text.docx](https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration/files/7896939/2022.release.-.text.docx)

**Comment by SophieMBennett** [comment]
@nrshapiro I've updated the right info box on the homepage with a link to the 'news release' pop-up, and added a pop-up with updated text across the language settings.

With the German setting the pop-up appears with an additional banner that seems to be linked to what is entered in this 'Language specific message' box - can I delete this wording? None of the other language settings has anything in this box except Spanish.

![notification](https://user-images.githubusercontent.com/83074920/150381126-13480d96-edb5-42e1-a30c-0eddc589a41c.PNG)

I hope I have got the embargo years correct - 2016 for 5 year; 2018 for 3 year.

Once you run the statistics, I will update the other details like number of articles and pages, as shown on homepage.

**Comment by davidtuckett** [comment]
Great work Sophie

**Comment by SophieMBennett** [comment]
@davidtuckett @nrshapiro based on your recent emails I've redrafted the IJPOpen info for the 'news release'

New:
IJPOpen articles and commentary are accessible to view for all PEP-Web subscribers. Tip: Look for the “speech bubbles” icon, located next to the article’s “print” and “download” icons to open and view the discussion. To join in, register for a free username via Disqus.

Old:
IJPOpen articles and comments are accessible to all PEP-Web subscribers. Those who are already registered with IJPOpen can join the discussion now. Those who wish to participate in the discussion can register for free via their PaDS account (select "New IJP order"). Tip: look for the "speech bubbles" icon, located next to the "print" and "download" icons of the article to display.

**Comment by nrshapiro** [comment]
@SophieMBennett  - Yes, you have the right years, but for the record know that there are journals with "odd' (nonstandard) embargos.  All the embargo values are listed in the Admin interface, as this is what the client uses to show the dates (which currently incorrectly "turn over" to a new release on Jan 1).

Here's the APPROXIMATE statistics  based on my local copy of the server (I can't run it against stage yet until there's another update).  These numbers will vary though until the final release on Monday since I'm (trying) to work on data as well as all the issues coming up with IJPOpen, PaDS, subscriptions, etc.  If you have an admin account, you can get these once logged in as 

https://stage-api.pep-web.org/docs#/Session/session_status_v2_Session_Status__get?moreinfo=true&client_id=4

<!DOCTYPE html><html><body><p>This release of PEP-Web contains the complete text and illustrations of 83 premier journals in psychoanalysis, 100 classic psychoanalytic books, 104 videos, and the full text and editorial notes of the 24 volumes of the Standard Edition of the Complete Psychological Works of Sigmund Freud as well as the 19 volume German Freud Standard Edition Gesammelte Werke.  It spans over 110 publication years and contains the full text of articles whose source ranges from 1911 through 2021.</p><p>There are over 139936 articles and 18773 figures and illustrations that originally resided on 2591 volumes with over 1.25 million printed pages. In hard copy, the PEP Archive represents a stack of paper more than 409 feet high and weighing over 5 tons!</p><p>The journals (with article counts) include:<ol><li>Almanach der Psychoanalyse  - 291</li><li>American Imago - 2119</li><li>American Journal of Psychoanalysis - 3303</li><li>Annual of Psychoanalysis - 631</li><li>Articles of Interest on the Web (text searchable but only citation data returned) - 23</li><li>Attachment: New Directions in Relational Psychoanalysis and Psychotherapy - 615</li><li>British Journal of Psychotherapy - 2879</li><li>Bulletin of the American Psychoanalytical Association - 403</li><li>Bulletin of the Anna Freud Centre - 437</li><li>Bulletin of the International Psycho-Analytical Association - 700</li><li>Canadian Journal of Psychoanalysis - 1014</li><li>Chinese Annual of Psychoanalysis - 9</li><li>Contemporary Psychoanalysis - 2543</li><li>Couple and Family Psychoanalysis - 368</li><li>Division Review - 425</li><li>Fort Da - 698</li><li>Free Associations - 716</li><li>Gender and Psychoanalysis - 158</li><li>IJP Open - Open Peer Review and Debate - 677</li><li>Imago - 1210</li><li>International Forum of Psychoanalysis - 1178</li><li>International Journal of Applied Psychoanalytic Studies - 691</li><li>International Journal of Psychoanalysis  - 11915</li><li>International Journal of Psychoanalysis en Espanol - 188</li><li>International Journal of Psychoanalytic Self Psychology - 517</li><li>International Review of Psychoanalysis - 1112</li><li>Internationale Psychoanalyse - 209</li><li>Internationale Zeitschrift für Psychoanalyse - 2771</li><li>Jahrbuch der Psychoanalyse - 864</li><li>Jahrbuch für psychoanalytische und psychopathologische Forschung - 121</li><li>Journal of Analytical Psychology - 4156</li><li>Journal of Applied Psychoanalytic Studies - 223</li><li>Journal of Child Psychotherapy - 1596</li><li>Journal of Clinical Psychoanalysis - 591</li><li>Journal of Infant, Child & Adolescent Psychotherapy - 666</li><li>Journal of Psychological Therapies - 104</li><li>Journal of the American Academy of Psychoanalysis - 2325</li><li>Journal of the American Psychoanalytic Association - 5584</li><li>L'Annata Psicoanaltica Internazionale - 139</li><li>L'anneé Psychanalytique Internationale - 211</li><li>Luzifer-Amor: Zeitschrift zur Geschichte der Psychoanalyse - 1209</li><li>Modern Psychoanalysis - 1093</li><li>Neuropsychoanalysis - 892</li><li>Oedipus Annual - Greek Annual Psychoanalytic Review - 20</li><li>Organizational and Social Dynamics - 452</li><li>Progress in Self-Psychology - 400</li><li>Psicoterapia e Scienze Umane - 3033</li><li>Psikanaliz Yazıları - 526</li><li>Psyche - Zeitschrift für Psychoanalyse - 8522</li><li>Psychoanalysis and Contemporary Science - 87</li><li>Psychoanalysis and Contemporary Thought - 482</li><li>Psychoanalysis and History - 515</li><li>Psychoanalysis and Psychotherapy in China - 91</li><li>Psychoanalysis, Self, and Context - 262</li><li>Psychoanalytic Books - 1203</li><li>Psychoanalytic Dialogues - 2109</li><li>Psychoanalytic Inquiry - 2207</li><li>Psychoanalytic Perspectives - 798</li><li>Psychoanalytic Psychology - 1881</li><li>Psychoanalytic Psychotherapy - 1271</li><li>Psychoanalytic Quarterly - 17042</li><li>Psychoanalytic Review - 6841</li><li>Psychoanalytic Social Work - 502</li><li>Psychoanalytic Study of the Child - 1618</li><li>Psychoanalytische Bewegung - 423</li><li>Psychodynamic Psychiatry - 493</li><li>Revista de Psicoanálisis - 1388</li><li>Revista de Psicoanálisis  - 3490</li><li>Revue Belge de Psychanalyse - 884</li><li>Revue Roumaine de Psychanalyse - 400</li><li>Revue française de psychanalyse - 8914</li><li>Revue psychoanalytická psychoterapie - 535</li><li>Rivista Italiana di Psicoanalisi - 91</li><li>Rivista di Psicoanalisi - 4053</li><li>Scandinavian Psychoanalytic Review - 967</li><li>Studies in Gender and Sexuality - 728</li><li>The International Journal of Forensic Psychotherapy - 65</li><li>The Italian Psychoanalytic Annual - 166</li><li>Tijdschrift voor psychoanalyse - 1945</li><li>Uluslararası Psikanaliz Yıllığı / The International Journal of Psychoanalysis Turkish Annual - 161</li><li>Zeitschrift für psychoanalytische Pädagogik - 753</li><li>Zentralblatt für Psychoanalyse - 1081</li><li>Ετήσια ελληνική έκδοση - 68</li></ol></p><p>All sources (with article counts) include:<ol><li>Almanach d. PsA. - 291</li><li>Am. Imago - 2119</li><li>Am. J. Psychoanal. - 3303</li><li>Anna Freud Ctr. - 2</li><li>Annu. Psychoanal. - 631</li><li>Articles of Interest on the Web - 23</li><li>Attach: New Dir. Rel. Psychoanal. Psychother. - 615</li><li>Bos. Psychoanal. Soc. Inst. - 1</li><li>Brit. J. Psychother. - 2879</li><li>Bul. Amer. Psychoanal. Assn. - 403</li><li>Bul. Anna Freud Centre - 437</li><li>Bul. Int. Psychoanal. Assn. - 700</li><li>Can. J. Psychoanal. - 1014</li><li>Chi Annual of Int. J. Psychoanal. - 9</li><li>Contemp. Psychoanal. - 2543</li><li>Cpl. Fam. Psychoanal. - 368</li><li>Div. Rev. - 425</li><li>Fort Da - 698</li><li>Free Associations - 716</li><li>Gender and Psychoanal. - 158</li><li>Gesammelte Werke - 451</li><li>IJP Open - 677</li><li>Imago - 1210</li><li>Inst. Psychoanal. UK AV Proj. - 16</li><li>Int. Forum Psychoanal. - 1178</li><li>Int. J.\r\nPsychoanal. Turkish Annu. - 161</li><li>Int. J. Appl. Psychoanal. Stud. - 691</li><li>Int. J. Forens. Psychoanal. - 65</li><li>Int. J. Psychoanal. - 11915</li><li>Int. J. Psychoanal. Es. - 188</li><li>Int. J. Psychoanal. Self Psychol. - 517</li><li>Int. Psycho-Anal. Lib. - 628</li><li>Int. Psychoanalyse - 209</li><li>Int. Rev. Psycho-Anal. - 1112</li><li>Int. Z. Psychoanal. - 2771</li><li>Ital. Psychoanal. Annu. - 166</li><li>J. Am. Acad. Psychoanal. Dyn. Psychiatr. - 2325</li><li>J. Amer. Psychoanal. Assn. - 5584</li><li>J. Anal. Psychol. - 4156</li><li>J. Appl. Psychoanal. Stud. - 223</li><li>J. Child Psychother. - 1596</li><li>J. Clin. Psychoanal. - 591</li><li>J. Infant Child Adolesc. Psychother. - 666</li><li>J. Psych. Ther. - 104</li><li>J. Revista de Psicoanal. - 1388</li><li>Jahrb. Psychoanal. - 864</li><li>Jahrb. Psychoanalyt. Psych. Forsch. - 121</li><li>L'Annata Psicoanal. Int. - 139</li><li>L'Annee Psychanal. Int. - 211</li><li>Luzifer-Amor - 1209</li><li>Mod. Psychoanal. - 1093</li><li>NY Psychoanal. Soc. Inst. - 1</li><li>Neurpsychoanalysis - 892</li><li>New Lib. of Psycho-Anal. - 18</li><li>Oed. Ann. - 20</li><li>Organ. Soc. Dyn. - 452</li><li>PEP Vid. Coll. - 23</li><li>PEP Vid. Grants - 7</li><li>PEP/UCL Top Authors Proj. - 40</li><li>Progr. Self Psychol. - 400</li><li>Psa. Books - 1203</li><li>Psikanaliz Yazıları - 526</li><li>Psyche - 8522</li><li>Psychoanal. Bew. - 423</li><li>Psychoanal. Contemp Sci - 87</li><li>Psychoanal. Contemp Thought - 482</li><li>Psychoanal. Cult. Soc. - 91</li><li>Psychoanal. Dial. - 2109</li><li>Psychoanal. Hist. - 515</li><li>Psychoanal. Inq. - 2207</li><li>Psychoanal. Persp. - 798</li><li>Psychoanal. Psychol. - 1881</li><li>Psychoanal. Psychother. - 1271</li><li>Psychoanal. Psychother. China - 327</li><li>Psychoanal. Q. - 17042</li><li>Psychoanal. Rev. - 6841</li><li>Psychoanal. Self Cxt. - 262</li><li>Psychoanal. Soc. Work - 502</li><li>Psychoanal. Study Child - 1618</li><li>Psychodyn. Psi. - 493</li><li>Psychoter. Sci. U. - 3033</li><li>Rev. Belg. Psychanal. - 884</li><li>Rev. Psicoanál.  - 3490</li><li>Rev. fr. psychanal. - 8914</li><li>Rev. psychoanal. psychoter. - 535</li><li>Rivista Italian Psicoanal. - 91</li><li>Rivista Psicoanal. - 4053</li><li>Rom. J. Psychoanal. - 400</li><li>San Fran. Ctr Psychoanal. - 4</li><li>Scand. Psychoanal. Rev. - 967</li><li>Soc. Psi. It. - 1</li><li>Standard Edition - 352</li><li>Stud. Gend. Sex. - 728</li><li>The Philoctetes Center - 2</li><li>Tijdschr. Psychoanal. - 1945</li><li>Univ. Coll. London Vid. Coll. - 2</li><li>Z. Psychoanalyt Pädagogik - 753</li><li>Zbl. Psyca - 1081</li><li>Ετήσια ελληνική έκδοση - 68</li></ol></p></body></html>

**Comment by nadinelevinson** [comment]
Thank you to both of you. 
N

Sent from Nadine Levinson’s Cell
949 573-7500
She is currently “On the run”

**Comment by nrshapiro** [comment]
Actually, if you look in my journal list No. 5 should not be counted.  So 82 journals, not counting PCAS.
