### ISSUE TITLE
Select Expert Pick Graphics

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#3]
Expert Pick graphics are selected from the Dropbox folder: PhotosInterestingForPOTD (in the PEPForAll folder).

You can copy any from the _Full Set - Delete Whatever_ folder into it, and it will be picked at random for the Expert Pick Graphic of the day.

**Comment by SophieMBennett** [comment]
Hi Neil - quick question about image quality when viewing the graphics in dropbox. Should I assume the image quality will be better once on the new website? I don't want to delete something due to poor quality and then find it would work okay on the site.

**Comment by nrshapiro** [comment]
@SophieMBennett 

No, those are all the originals as they exist in PEP-Web.  Assuming you're looking at them on a decent computer screen, and at the size (reduced) it would be to fit in the Expert Picks area, they are as bad as they look to you on your screen.

**Comment by SophieMBennett** [comment]
@nrshapiro 

A non-urgent question related to using images on social media. I will mostly be posting the Graphic of the Day and the source (journal, author, etc) is identified on the new site. If I want to use an image direct from the archive is there a way to better understand the id codes to locate the source and so include complete reference in the SM post? i.e., is there a key list for the codes? Not urgent, but in time it would be a good way to publicize library content. As an e.g. RIPA_A_1686305_ILG0018.jpg

**Comment by SophieMBennett** [comment]
@nrshapiro I noticed you had moved all the images in the sub-folder 'Portraits' to PhotosinterestingforPOTD, I am yet to sort through these and some were not good quality images. Is there a reason for the move and can I delete those that are poor quality? As a general update, I am gradually making my way through the main cache in Full Set - Delete Whatever working from the bottom up and moving good quality images into PhotosinterestingforPOTD.

**Comment by nrshapiro** [comment]
@SophieMBennett - I noticed too many of the same images showing up repeatedly on the front page of PEP-Web, so I wanted to increase the candidate set size to stir it up.  It looked like the portrait set was pretty good to me.  Besides those, I went through myself and moved some ones I thought interesting to PhotosinterestingforPOTD.  I was the one who picked the initial set there to get things rolling at the start, and I've added to it a few times, though the last few times I left the originals in the other set so you could go through it.  But I had a different idea this time.

I realize the set is humongous to go through and I didn't realize that it would be this much work for you.  When we wanted to get a start, before D. put you on that task, I created PhotosInterestingforPOTD and that's what the queue is now based on.  It would have otherwise been based on the one you are working on.

So:

1) Rather than deleting; I think you can just go through and pick photos/images that are interesting and MOVE them to PhotosInterestingforPOTD

2) If you see any in PhotosInterestingforPOTD that are particularly low resolution or you don't think will be interesting for that use, you can delete those.  Remember:
   a) portrait mode rather than landscape mode usually works best
   b) The images are not displayed very large, so it doesn't have to be any larger than 200x400 or so to show up well.  

3) Then, let me know when you are done and we will just delete the other folder.  I think that will be easier and quicker to do than your original task.

**Comment by SophieMBennett** [comment]
@nrshapiro If there is a particular deadline by which time you need a permanent selection of images for the new site please let me know as I will focus my efforts on this project. I had noticed that the Graphic of the Day had started repeating recently and have been moving images into the PhotosInterestingforPOTD to supplement what is published, hence I was suprised when all the portraits appeared! I wasn't given a timeline or logistical/technical parametres and have been working on this issue when I can. Deleting the images from the main folder does take time, but the result is a really great cache of images which can only benefit the new site, plus they are useful for social media/marketing purposes as we are advertising the site via the graphics and expert picks.

**Comment by nrshapiro** [comment]
@SophieMBennett There's no deadline as far as I am concerned, but understand that while you are working on it, the set isn't being used for anything, and meanwhile, the total graphic set is growing each month as new journals come in (and I've not been adding those to the folder).  Of course, thinking about it, we don't want to use anything that's in current content, because the context of the graphic will not be accessible, since current content is abstract only.  So really, it's only once a year that new graphics should be added to the set--those moving out of current content in January.

You can work on it as long as you want, and you can then use that set for whatever you want.  But I still think it's better to move (or in this new context, copy) images into PhotosInterestingforPOTD as you go through them--which means that the candidate set will continue to grow and that will keep POTD fresh, even if it took you a long time to finish the walkthrough of that set.

**Comment by SophieMBennett** [comment]
@nrshapiro Thanks for letting me know the parametres involved, it's very helpful. I have now gone through PhotosInterestingforPOTD and all the images currently in there are good for use on the site. 

From now on, as I go through Full Set - Delete Whatever, I will copy images into PhotosInterestingforPOTD (rather than deleting) so that what is to be found in PhotosInterestingforPOTD is ready for direct use. This candidate set will then be more regularly updated and refresh the website. Please let me know if I have missed anything!

**Comment by nrshapiro** [comment]
@SophieMBennett   Sounds good.

**Comment by nrshapiro** [comment]
@SophieMBennett - For publishing the new database, I will have to resolve differences between the Admin database on Production and on Stage.  I did notice a while back that you (or someone) had been making changes on Production.  The protocol, when we get things into a regular flow is to make the changes on Stage and then push Stage Admin to production.  But I do understand at this point that this presents a logistic problem--since there's no easy way for anyone but myself right now to push the Stage Admin to Production, and during the journal update period September to February I make changes to Admin on Production that aren't ready to push to Production.  I will be thinking of ways to work this out.

Meanwhile, I will have to resolve where changes might have been made on Admin Production (I did this a month or so again to sync the databases), and then Stage needs to be pushed to Production.  While doing so, I could easily delete the graphics from the current entries in the Expert Picks queue.  It's easier to delete them in the database than it is in the Admin interface (which requires resetting up those entries.  

So: 
1. Don't make any changes to the Production Admin interface over the next week or they will be lost.  Let's discuss a better method in February (or more simply, just do it on Stage).
2. If you are ok with it, I will clean up the current Expert Picks Queue.  If it's ok with you then, I will delete them--I'm tired of seeing the same pictures come up day after day.  Please let me know soon.

And, in answer to a question above:

3. Most graphics (but not all) graphics use the same naming system we use for articles.  This is described here: http://support.pep-web.org/publishersarea/supplying-materials/supplying-materials-to-pep/   This makes it identifiable as to what article it's from.  In addition, you can do a SmartSearch for graphic identifiers using the field search syntax field:value, e.g.,
 
art_graphic_list:psc52037
art_graphic_list:AIM.008.0129A.FIG001

Though if the article ID is in the figure name, as in the second example, you save a click and go right to the article just putting the article id SmartSearch

AIM.008.0129A

Note that you should not put the file extension in the search (i.e., no .jpg)

**Comment by SophieMBennett** [comment]
_So:

Don't make any changes to the Production Admin interface over the next week or they will be lost. Let's discuss a better method in February (or more simply, just do it on Stage)._ 

That's fine - FYI I'm currently updating the journal publisher info on Stage (English setting)

_If you are ok with it, I will clean up the current Expert Picks Queue. If it's ok with you then, I will delete them--I'm tired of seeing the same pictures come up day after day. Please let me know soon._

 Assuming you just mean delete the photos connected to the articles (not the articles) - yes, I think this would be a very good idea as it has become very dull.
 
 Thank you for the info about how to locate images in articles.
 
 It's not urgent about if/when there will be new images added to the Full Set - Delete Whatever folder, I will just keep an eye on it.

**Comment by nrshapiro** [comment]
@SophieMBennett 

Thanks for the quick reply.  I've copied over any figure graphics that was created after 7/10/2011.  (Approximately after when the last batch ended.)

A word of caution that just came to mind about the graphics which are not using the article ID.  While YOU can find the article it's in given the method above, I don't think the client APP would be able to (you can try it, but I'm pretty sure while the graphic will show, you won't be able to click on it to go to the article--and worse, you may get a 404 error).  So if you use one of those, you should rename it using the standard articleID nomenclature.  The FIG part doesn't matter, since I think it just goes to the top of the article anyway.
