### ISSUE TITLE
Select Expert Pick Articles

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#4]
The articles that are Expert Picks are set up in admin mode in the General area on Stage (and then copied to Production) when I do a configuration push.  **Do not do Admin editing on Production.**  You enter the Article ID of the expert pick article you want in the queue, adding it to the end of the queue.  As days go by, eventually, it will get to that entry.  If you know when the queue was "started", then you can figure out dates, but otherwise, you cannot.

![image](https://user-images.githubusercontent.com/4837554/114081800-02c81b00-987b-11eb-9d0f-4228ec3e282c.png)

You can optionally specify a graphic ID for that day...or put an "*" in the graphic field for a random pick.  The queue shown above is from an earlier version of the site, before that was implemented, so there are no examples of random picks there, but it should work that way now.

**Comment by nrshapiro** [comment]
I keep wondering why I keep seeing the same expert pick graphics and articles.

Here's the expert pick list as of today...looks a lot like the one from before, with some added.

![image](https://user-images.githubusercontent.com/4837554/144052599-f426769d-2cd2-42ff-85d9-c5ac059eb65d.png)


You should know:
1) When it gets to the end of this list, it starts over
2) If you include a graphic ID, it uses it.  Use "*" to choose a random graphic

Since that wasn't true when the list was first edited, even if you want the list to keep repeating (by not removing old entries), you should reenter those and at least let it pick a random graphic for variety.  Otherwise, the only random graphic that will be picked is the last entry that was added.  The repeat graphic makes it obvious that this is a repeat, perhaps moreso than the article, at least for a non-psychoanalyst like me.

**Comment by davidtuckett** [comment]
Thanks Neil - we are aware of this and other similar issues but we have had to set priorities and this is not one yet.
