### ISSUE TITLE
Create/Upload Preview Videos and Captions

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#5]
We need preview videos for as many PEP videos as possible.  They don't have to be the summary type videos you produced for the top authors project, they can simply be the first 30-90 seconds of the video itself.

For each video, please provide the transcription caption file in .vtt (WebVtt) format.  

Wistia lets you download the .srt files

![image](https://user-images.githubusercontent.com/4837554/114189877-ae737880-9918-11eb-8468-fea5728f82db.png)

And from there the .srt files can be converted to WebVTT for free on many online sites, for example:

- https://www.rev.com/captionconverter
- https://gotranscript.com/subtitle-converter

Files should be named with the video article ID you see on PEP-Web, and the suffix .preview.  For example:

- PEPTOPAUTHVS.001.0013A.preview.jpg
- PEPTOPAUTHVS.001.0013A.preview.mp4
- PEPTOPAUTHVS.001.0013A.preview.srt
- PEPTOPAUTHVS.001.0013A.preview.vtt

Files should be placed in our dropbox at:
    - PEP's shared workspace\PEP for All\Inventory\Photos\AWSProd Video Previews

**Comment by SophieMBennett** [comment]
Hi Neil, 
I've been adding .srt and .vtt files for previews to the dropbox. Can you let me know if you want me to add MP4, jpg, png where they are missing and if so, 
1) Is there a particular size preference/format that you want for the MP4 from the download options in Wistia? 
2) For jpg & png - There is an option to download a png from Wistia (offered when you download the video), are you then converting this to jpg and are there size preferences?
Please let me know your process and I can aim to put together full sets of files for each preview.
Is it okay at some point to add folders within the dropbox file to seperate previews from different projects i.e., PEPTOPAUTHAV, PEPVS, IJPVS, etc?

**Comment by nrshapiro** [comment]
@SophieMBennett 

1.  Download the full-size video
2. Yes.  Use the size you download.  My file manager does it easily--if you're using a PC, you might have DT purchase it for you...it's absolutely essential to all the PEP file naming/conversion and management tasks I do.  [Called Directory Opus](https://www.gpsoft.com.au/order_intro.html).  There's a trial on Directory Opus so you can try it first.  You can also use online converters: https://www.freeconvert.com/png-to-jpg  
3. No, please don't do subfolders -- the prefixes will help sort by source.  The AWS folder they're copied to and used from doesn't want subfolders.

**Comment by SophieMBennett** [comment]
Thanks Neil. I am now using the trial version of Directory Opus light. 
Quick question about videos - occasionally the full-size video comes up as an .m4v file. Can I use these / should I always opt for an mp4 version?

**Comment by SophieMBennett** [comment]
@nrshapiro 

I have uploaded the relevant files for all the preview videos that are currently available. A couple of notes:

1. There are no .srt /.vtt files for the following videos:
pepgrantvs.001.0006a.preview (no spoken audio)
ipsavs.001a.0007a.preview  (captions embedded in video)

2. I have uploaded previews for the following Top Authors videos that are not yet published:
peptopauthvs.001.0033a.preview
peptopauthvs.001.0034a.preview
peptopauthvs.001.0035a.preview
peptopauthvs.001.0036a.preview
peptopauthvs.001.0037a.preview

If there is an opportunity to have the full videos published as part of the process that would be great. Let me know if you need any other info, or want me to resend the XML. 

I am speaking to Angela today about creating previews for the remaining videos on the site.
